// <auto-generated />
using System;
using CarBookingProject_0.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBookingProject_0.Migrations
{
    [DbContext(typeof(CarBookingProject_0Context))]
    partial class CarBookingProject_0ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarBookingProject_0.Domain.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comments")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FeedbackDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Feedback");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Comments = "Great ride! The driver was very professional.",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4825),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4826),
                            FeedbackDateTime = new DateTime(2024, 12, 6, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4810),
                            Rating = 5,
                            RideId = 1,
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Comments = "The ride was okay, but the car was a bit dirty.",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4830),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4830),
                            FeedbackDateTime = new DateTime(2024, 12, 7, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4829),
                            Rating = 3,
                            RideId = 2,
                            UpdatedBy = "System",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("Latitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<decimal?>("Longitude")
                        .HasPrecision(10, 6)
                        .HasColumnType("decimal(10,6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Location");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Marina Bay Sands, 10 Bayfront Ave",
                            City = "Singapore",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4986),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4987),
                            Latitude = 1.290270m,
                            Longitude = 103.851959m,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Sentosa Island",
                            City = "Singapore",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4989),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(4989),
                            Latitude = 1.352083m,
                            Longitude = 103.819836m,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("AmountPaid")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TransactionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Payment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AmountPaid = 25.50m,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5064),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5065),
                            PaymentStatus = "Completed",
                            PaymentType = "Credit Card",
                            RideId = 1,
                            TransactionDateTime = new DateTime(2024, 12, 8, 20, 33, 35, 863, DateTimeKind.Local).AddTicks(5063),
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AmountPaid = 30.00m,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5067),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5067),
                            PaymentStatus = "Pending",
                            PaymentType = "Cash",
                            RideId = 2,
                            TransactionDateTime = new DateTime(2024, 12, 8, 20, 53, 35, 863, DateTimeKind.Local).AddTicks(5066),
                            UpdatedBy = "System",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.Promotion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PromotionCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Promotion");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5121),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5121),
                            DiscountAmount = 10.00m,
                            EndDate = new DateTime(2024, 12, 28, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5120),
                            PromotionCode = "SAVE10",
                            StartDate = new DateTime(2024, 11, 28, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5118),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5124),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5124),
                            DiscountAmount = 20.00m,
                            EndDate = new DateTime(2024, 12, 23, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5123),
                            PromotionCode = "WELCOME20",
                            StartDate = new DateTime(2024, 12, 3, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5123),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DropoffTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PickupTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("PromotionId")
                        .HasColumnType("int");

                    b.Property<decimal>("RideCost")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RideStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Ride");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5174),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5174),
                            DropoffTime = new DateTime(2024, 12, 8, 20, 3, 35, 863, DateTimeKind.Local).AddTicks(5172),
                            LocationId = 1,
                            PickupTime = new DateTime(2024, 12, 8, 19, 3, 35, 863, DateTimeKind.Local).AddTicks(5171),
                            PromotionId = 1,
                            RideCost = 25.50m,
                            RideStatus = "Completed",
                            UpdatedBy = "System",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5177),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5177),
                            DropoffTime = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5176),
                            LocationId = 2,
                            PickupTime = new DateTime(2024, 12, 8, 20, 3, 35, 863, DateTimeKind.Local).AddTicks(5175),
                            PromotionId = 2,
                            RideCost = 30.00m,
                            RideStatus = "Ongoing",
                            UpdatedBy = "System",
                            UserId = 2
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("RoleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5225),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5226),
                            RoleType = "Driver",
                            UpdatedBy = "System",
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5227),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5227),
                            RoleType = "Passenger",
                            UpdatedBy = "System",
                            UserId = 0
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcceptanceRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CarLicense")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DateOfBirth")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("DrivingExperience")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FrequentLocations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PreferredPickupTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AcceptanceRate = "",
                            Address = "Jurong East",
                            CarLicense = "",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5279),
                            DateOfBirth = "05/03/2001",
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5280),
                            DrivingExperience = "",
                            Email = "Jordan01239@gmail.com",
                            FrequentLocations = "Jurong East, Clementi",
                            Gender = "Male",
                            Name = "Jordan",
                            PhoneNumber = "97593043",
                            PreferredPickupTime = "Morning",
                            RoleId = 0,
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AcceptanceRate = "75.5%",
                            Address = "Jurong West",
                            CarLicense = "SGX1234A",
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5282),
                            DateOfBirth = "22/10/2000",
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5283),
                            DrivingExperience = "2 years",
                            Email = "Jeff019231@gmail.com",
                            FrequentLocations = "Jurong West, Pioneer",
                            Gender = "Male",
                            Name = "Jeff",
                            PhoneNumber = "93843943",
                            PreferredPickupTime = "Morning",
                            RoleId = 0,
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("CarBookingProject_0.Domain.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Manufacturer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MaximumPassengers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Year")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Vehicle");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5335),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5335),
                            LicensePlate = "MBX3829B",
                            Manufacturer = "Honda",
                            MaximumPassengers = "4",
                            Model = "Corolla",
                            Status = "Active",
                            UpdatedBy = "System",
                            UserId = 0,
                            Year = "2020"
                        },
                        new
                        {
                            Id = 2,
                            CreatedBy = "System",
                            DateCreated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5337),
                            DateUpdated = new DateTime(2024, 12, 8, 21, 3, 35, 863, DateTimeKind.Local).AddTicks(5338),
                            LicensePlate = "JKX8273C",
                            Manufacturer = "Toyota",
                            MaximumPassengers = "4",
                            Model = "Civic",
                            Status = "Active",
                            UpdatedBy = "System",
                            UserId = 0,
                            Year = "2017"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
